// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SampleDatabaseBuilder.Migrations
{
    [DbContext(typeof(SamplesContext))]
    [Migration("20241226063947_AddDisplayOrder")]
    partial class AddDisplayOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AnalysisItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnalysisItemInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisItemInfoId");

                    b.HasIndex("SampleId");

                    b.ToTable("AnalysisItems");
                });

            modelBuilder.Entity("AnalysisItemCatagoryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnalysisItemCatagoryInfos");
                });

            modelBuilder.Entity("AnalysisItemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnalysisItemCatagoryInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisItemCatagoryInfoId");

                    b.ToTable("AnalysisItemInfos");
                });

            modelBuilder.Entity("FoodCatagory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodCatagories");
                });

            modelBuilder.Entity("Sample", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodCatagoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodCatagoryId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("AnalysisItem", b =>
                {
                    b.HasOne("AnalysisItemInfo", "AnalysisItemInfo")
                        .WithMany()
                        .HasForeignKey("AnalysisItemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sample", "Sample")
                        .WithMany("AnalysisItems")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisItemInfo");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("AnalysisItemInfo", b =>
                {
                    b.HasOne("AnalysisItemCatagoryInfo", "AnalysisItemCatagoryInfo")
                        .WithMany("AnalysisItemInfos")
                        .HasForeignKey("AnalysisItemCatagoryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisItemCatagoryInfo");
                });

            modelBuilder.Entity("Sample", b =>
                {
                    b.HasOne("FoodCatagory", "FoodCatagory")
                        .WithMany()
                        .HasForeignKey("FoodCatagoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodCatagory");
                });

            modelBuilder.Entity("AnalysisItemCatagoryInfo", b =>
                {
                    b.Navigation("AnalysisItemInfos");
                });

            modelBuilder.Entity("Sample", b =>
                {
                    b.Navigation("AnalysisItems");
                });
#pragma warning restore 612, 618
        }
    }
}
